/**
 * AI Prompt Composer API
 * This API is for quickly adjusting prompt data to improve LLM Output
 *
 * The version of the OpenAPI document: 0.2
 * Contact: trompell@th-brandenburg.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about the error.
 */
export interface ErrorInformation { 
    /**
     * Some unique error code.
     */
    code: number;
    /**
     * Error message.
     */
    message: string;
}

