from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from AiPromptComposerApi.models.base_model import Model
from AiPromptComposerApi import util


class PostPromptResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, response=None):  # noqa: E501
        """PostPromptResponse - a model defined in OpenAPI

        :param response: The response of this PostPromptResponse.  # noqa: E501
        :type response: str
        """
        self.openapi_types = {
            'response': str
        }

        self.attribute_map = {
            'response': 'response'
        }

        self._response = response

    @classmethod
    def from_dict(cls, dikt) -> 'PostPromptResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostPromptResponse of this PostPromptResponse.  # noqa: E501
        :rtype: PostPromptResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def response(self) -> str:
        """Gets the response of this PostPromptResponse.

        The response of the llm  # noqa: E501

        :return: The response of this PostPromptResponse.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response: str):
        """Sets the response of this PostPromptResponse.

        The response of the llm  # noqa: E501

        :param response: The response of this PostPromptResponse.
        :type response: str
        """

        self._response = response
